name: Android Test CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle Unit Test
      run: ./gradlew testDebugUnitTest
    - name: Gradle Test Report
      run: asadmansr/android-test-report-action@v1.2.0
      if: ${{ allways() }}
